/labjack_uc3_hv:
  ros__parameters:
    channel/0/active: true
    channel/0/analog/gain: 1.0
    channel/0/analog/negative_channel: 31
    channel/0/analog/offset: 0.0
    channel/0/is_analog: true
    channel/0/period: 1.0
    channel/1/active: false
    channel/1/analog/gain: 1.0
    channel/1/analog/negative_channel: 31
    channel/1/analog/offset: 0.0
    channel/1/is_analog: true
    channel/1/period: 1.0
    channel/10/active: true
    channel/10/analog/gain: 1.0
    channel/10/analog/negative_channel: 31
    channel/10/analog/offset: 0.0
    channel/10/is_analog: false
    channel/10/period: 1.0
    channel/11/active: false
    channel/11/analog/gain: 1.0
    channel/11/analog/negative_channel: 31
    channel/11/analog/offset: 0.0
    channel/11/is_analog: false
    channel/11/period: 1.0
    channel/12/active: false
    channel/12/analog/gain: 1.0
    channel/12/analog/negative_channel: 31
    channel/12/analog/offset: 0.0
    channel/12/is_analog: false
    channel/12/period: 1.0
    channel/13/active: false
    channel/13/analog/gain: 1.0
    channel/13/analog/negative_channel: 31
    channel/13/analog/offset: 0.0
    channel/13/is_analog: false
    channel/13/period: 1.0
    channel/14/active: false
    channel/14/analog/gain: 1.0
    channel/14/analog/negative_channel: 31
    channel/14/analog/offset: 0.0
    channel/14/is_analog: false
    channel/14/period: 1.0
    channel/15/active: false
    channel/15/analog/gain: 1.0
    channel/15/analog/negative_channel: 31
    channel/15/analog/offset: 0.0
    channel/15/is_analog: false
    channel/15/period: 1.0
    channel/16/active: false
    channel/16/is_analog: false
    channel/16/period: 1.0
    channel/17/active: false
    channel/17/is_analog: false
    channel/17/period: 1.0
    channel/18/active: false
    channel/18/is_analog: false
    channel/18/period: 1.0
    channel/19/active: false
    channel/19/is_analog: false
    channel/19/period: 1.0
    channel/2/active: false
    channel/2/analog/gain: 1.0
    channel/2/analog/negative_channel: 31
    channel/2/analog/offset: 0.0
    channel/2/is_analog: true
    channel/2/period: 1.0
    channel/3/active: false
    channel/3/analog/gain: 1.0
    channel/3/analog/negative_channel: 31
    channel/3/analog/offset: 0.0
    channel/3/is_analog: true
    channel/3/period: 1.0
    channel/4/active: false
    channel/4/analog/gain: 1.0
    channel/4/analog/negative_channel: 31
    channel/4/analog/offset: 0.0
    channel/4/is_analog: false
    channel/4/period: 1.0
    channel/5/active: false
    channel/5/analog/gain: 1.0
    channel/5/analog/negative_channel: 31
    channel/5/analog/offset: 0.0
    channel/5/is_analog: false
    channel/5/period: 1.0
    channel/6/active: false
    channel/6/analog/gain: 1.0
    channel/6/analog/negative_channel: 31
    channel/6/analog/offset: 0.0
    channel/6/is_analog: false
    channel/6/period: 1.0
    channel/7/active: false
    channel/7/analog/gain: 1.0
    channel/7/analog/negative_channel: 31
    channel/7/analog/offset: 0.0
    channel/7/is_analog: false
    channel/7/period: 1.0
    channel/8/active: false
    channel/8/analog/gain: 1.0
    channel/8/analog/negative_channel: 31
    channel/8/analog/offset: 0.0
    channel/8/is_analog: false
    channel/8/period: 1.0
    channel/9/active: false
    channel/9/analog/gain: 1.0
    channel/9/analog/negative_channel: 31
    channel/9/analog/offset: 0.0
    channel/9/is_analog: false
    channel/9/period: 1.0
    frame_id: ''
    use_sim_time: false

